        .data
_s1:    .ascii  "shabi"
        .text
	b main
mod:
         move,$t1,$fp
         lw,$t0,-20($t1)
         move,$t2,$fp
         lw,$t1,-24($t2)
         move,$t3,$fp
         lw,$t2,-28($t3)
         div,$t0,$t1
         mflo,$t2
         move,$t0,$fp
         sw,$t2,-28($t0)
         move,$t1,$fp
         lw,$t0,-28($t1)
         move,$t2,$fp
         lw,$t1,-24($t2)
         move,$t3,$fp
         lw,$t2,-32($t3)
         mult,$t0,$t1
         mflo,$t2
         move,$t0,$fp
         sw,$t2,-32($t0)
         move,$t1,$fp
         lw,$t0,-20($t1)
         move,$t2,$fp
         lw,$t1,-32($t2)
         move,$t3,$fp
         lw,$t2,-36($t3)
         sub,$t2,$t0,$t1
         move,$t0,$fp
         sw,$t2,-36($t0)
         move,$t1,$fp
         lw,$t0,-36($t1)
         move,$t1,$fp
         lw,$t1,-4($t1)
         sw,$t0,-28($t1)
         move,$t1,$fp
         lw,$t0,-28($t1)
         move,$v0,$t0
         jr,$ra
gcd2:
$L0:
         move,$t2,$fp
         lw,$t1,-24($t2)
         move,$t2,$fp
         sw,$t1,-28($t2)
         move,$t1,$fp
         lw,$t1,-20($t1)
         sw,$t1,-16($sp)
         addi,$sp,$sp,-4
         move,$t1,$fp
         lw,$t1,-24($t1)
         sw,$t1,-16($sp)
         addi,$sp,$sp,-4
         addi,$sp,$sp,8
         move,$t1,$fp
         lw,$t1,-4($t1)
         sw,$fp,-4($sp)
         sw,$t1,-8($sp)
         sw,$ra,-12($sp)
         sw,$v0,-16($sp)
         move,$fp,$sp
         jal,mod
         move,$t2,$fp
         sw,$v0,-32($t2)
         lw,$fp,-4($sp)
         lw,$ra,-12($sp)
         lw,$v0,-16($sp)
         move,$t2,$fp
         lw,$t1,-32($t2)
         move,$t2,$fp
         sw,$t1,-24($t2)
         move,$t2,$fp
         lw,$t1,-28($t2)
         move,$t2,$fp
         lw,$t2,-20($t2)
         sw,$t1,0($t2)
         move,$t2,$fp
         lw,$t1,-24($t2)
         lw,$t1,0($t1)
         li,$t2,0
         move,$t4,$fp
         lw,$t3,-36($t4)
         seq,$t3,$t1,$t2
         move,$t1,$fp
         sw,$t3,-36($t1)
         move,$t2,$fp
         lw,$t1,-36($t2)
         beqz,$t1,$L0
         move,$t2,$fp
         lw,$t1,-20($t2)
         lw,$t1,0($t1)
         move,$t2,$fp
         lw,$t2,-4($t2)
         sw,$t1,-28($t2)
         move,$t2,$fp
         lw,$t1,-28($t2)
         move,$v0,$t1
         jr,$ra
gcd1:
         move,$t3,$fp
         lw,$t2,-24($t3)
         li,$t3,0
         move,$t5,$fp
         lw,$t4,-28($t5)
         seq,$t4,$t2,$t3
         move,$t2,$fp
         sw,$t4,-28($t2)
         move,$t3,$fp
         lw,$t2,-28($t3)
         beqz,$t2,$L1
         move,$t3,$fp
         lw,$t2,-20($t3)
         move,$t3,$fp
         lw,$t3,-4($t3)
         sw,$t2,-28($t3)
         b,$L2
$L1:
         move,$t2,$fp
         lw,$t2,-24($t2)
         sw,$t2,-16($sp)
         addi,$sp,$sp,-4
         move,$t3,$fp
         lw,$t2,-20($t3)
         move,$t4,$fp
         lw,$t3,-24($t4)
         move,$t5,$fp
         lw,$t4,-32($t5)
         div,$t2,$t3
         mflo,$t4
         move,$t2,$fp
         sw,$t4,-32($t2)
         move,$t3,$fp
         lw,$t2,-32($t3)
         move,$t4,$fp
         lw,$t3,-24($t4)
         move,$t5,$fp
         lw,$t4,-36($t5)
         mult,$t2,$t3
         mflo,$t4
         move,$t2,$fp
         sw,$t4,-36($t2)
         move,$t3,$fp
         lw,$t2,-20($t3)
         move,$t4,$fp
         lw,$t3,-36($t4)
         move,$t5,$fp
         lw,$t4,-40($t5)
         sub,$t4,$t2,$t3
         move,$t2,$fp
         sw,$t4,-40($t2)
         move,$t2,$fp
         lw,$t2,-40($t2)
         sw,$t2,-16($sp)
         addi,$sp,$sp,-4
         addi,$sp,$sp,8
         move,$t2,$fp
         lw,$t2,-4($t2)
         lw,$t2,-4($t2)
         sw,$fp,-4($sp)
         sw,$t2,-8($sp)
         sw,$ra,-12($sp)
         sw,$v0,-16($sp)
         move,$fp,$sp
         jal,gcd1
         move,$t3,$fp
         sw,$v0,-44($t3)
         lw,$fp,-4($sp)
         lw,$ra,-12($sp)
         lw,$v0,-16($sp)
         move,$t3,$fp
         lw,$t2,-44($t3)
         move,$t3,$fp
         lw,$t3,-4($t3)
         sw,$t2,-28($t3)
$L2:
         move,$t3,$fp
         lw,$t2,-28($t3)
         move,$v0,$t2
         jr,$ra
main:
         li,$v0,4
         la,$a0,_s1
         syscall
         li,$v0,5
         syscall
         move $t3,$v0
         move,$t4,$fp
         sw,$t3,-20($t4)
         li,$v0,5
         syscall
         move $t3,$v0
         move,$t4,$fp
         sw,$t3,-24($t4)
         move,$t3,$fp
         lw,$t3,-20($t3)
         sw,$t3,-16($sp)
         addi,$sp,$sp,-4
         move,$t3,$fp
         lw,$t3,-24($t3)
         sw,$t3,-16($sp)
         addi,$sp,$sp,-4
         addi,$sp,$sp,8
         move,$t3,$fp
         lw,$t3,-4($t3)
         sw,$fp,-4($sp)
         sw,$t3,-8($sp)
         sw,$ra,-12($sp)
         sw,$v0,-16($sp)
         move,$fp,$sp
         jal,gcd1
         move,$t4,$fp
         sw,$v0,-32($t4)
         lw,$fp,-4($sp)
         lw,$ra,-12($sp)
         lw,$v0,-16($sp)
         move,$t4,$fp
         lw,$t3,-32($t4)
         li,$v0,1
         move,$a0,$t3
         syscall
         move,$t4,$fp
         addi,$t4,$t4,-20
         move,$t5,$fp
         lw,$t5,-36($t5)
         sw,$t4,0($t5)
         move,$t4,$fp
         lw,$t4,-36($t4)
         lw,$t4,0($t4)
         sw,$t4,-16($sp)
         addi,$sp,$sp,-4
         move,$t4,$fp
         addi,$t4,$t4,-24
         move,$t5,$fp
         lw,$t5,-40($t5)
         sw,$t4,0($t5)
         move,$t4,$fp
         lw,$t4,-40($t4)
         lw,$t4,0($t4)
         sw,$t4,-16($sp)
         addi,$sp,$sp,-4
         addi,$sp,$sp,8
         move,$t4,$fp
         lw,$t4,-4($t4)
         sw,$fp,-4($sp)
         sw,$t4,-8($sp)
         sw,$ra,-12($sp)
         sw,$v0,-16($sp)
         move,$fp,$sp
         jal,gcd2
         move,$t5,$fp
         sw,$v0,-44($t5)
         lw,$fp,-4($sp)
         lw,$ra,-12($sp)
         lw,$v0,-16($sp)
         move,$t5,$fp
         lw,$t4,-44($t5)
         li,$v0,1
         move,$a0,$t4
         syscall
