        .data
        .text
         move,$fp,$sp
         sw,$fp,-4($sp)
         sw,$fp,-8($sp)
         b,main
fact:
         addi,$sp,$sp,-36
         move,$t1,$fp
         lw,$t1,-8($t1)
         lw,$t0,-20($t1)
         li,$t1,1
         move,$t3,$fp
         lw,$t2,-20($t3)
         sgt,$t2,$t0,$t1
         move,$t0,$fp
         sw,$t2,-20($t0)
         move,$t1,$fp
         lw,$t0,-20($t1)
         beqz,$t0,$L0
         move,$t1,$fp
         lw,$t1,-8($t1)
         lw,$t0,-20($t1)
         li,$t1,1
         move,$t3,$fp
         lw,$t2,-24($t3)
         sub,$t2,$t0,$t1
         move,$t0,$fp
         sw,$t2,-24($t0)
         move,$t1,$fp
         lw,$t0,-24($t1)
         move,$t1,$fp
         lw,$t1,-8($t1)
         sw,$t0,-20($t1)
         move,$t1,$fp
         lw,$t1,-8($t1)
         lw,$t0,-20($t1)
         li,$t1,1
         move,$t3,$fp
         lw,$t2,-28($t3)
         add,$t2,$t0,$t1
         move,$t0,$fp
         sw,$t2,-28($t0)
         move,$t0,$fp
         lw,$t0,-8($t0)
         sw,$fp,-4($sp)
         sw,$t0,-8($sp)
         sw,$ra,-12($sp)
         sw,$v0,-16($sp)
         move,$fp,$sp
         jal,fact
         lw,$fp,-4($sp)
         lw,$ra,-12($sp)
         move,$t1,$fp
         sw,$v0,-32($t1)
         lw,$v0,-16($sp)
         move,$t1,$fp
         lw,$t0,-28($t1)
         move,$t2,$fp
         lw,$t1,-32($t2)
         move,$t3,$fp
         lw,$t2,-36($t3)
         mult,$t0,$t1
         mflo,$t2
         move,$t0,$fp
         sw,$t2,-36($t0)
         move,$t1,$fp
         lw,$t0,-36($t1)
         move,$t1,$fp
         sw,$t0,-16($t1)
         b,$L1
$L0:
         li,$t0,1
         move,$t1,$fp
         sw,$t0,-16($t1)
$L1:
         move,$t1,$fp
         lw,$t0,-16($t1)
         move,$v0,$t0
         addi,$sp,$sp,36
         jr,$ra
main:
         addi,$sp,$sp,-24
         li,$t1,6
         move,$t2,$fp
         sw,$t1,-20($t2)
         move,$t1,$fp
         lw,$t1,-8($t1)
         sw,$fp,-4($sp)
         sw,$t1,-8($sp)
         sw,$ra,-12($sp)
         sw,$v0,-16($sp)
         move,$fp,$sp
         jal,fact
         lw,$fp,-4($sp)
         lw,$ra,-12($sp)
         move,$t2,$fp
         sw,$v0,-24($t2)
         lw,$v0,-16($sp)
         move,$t2,$fp
         lw,$t1,-24($t2)
         li,$v0,1
         move,$a0,$t1
         syscall
         addi,$sp,$sp,24
